/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Snail;

import Facade.CheckFacade;

public class StartMenu extends javax.swing.JFrame {

    private SnailGame snailGame;
    private CheckFacade checkFacade;
    boolean mode;

    public StartMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void startGame() {
        new SnailGame().start();
    }

    public void exitGame() {
        this.setVisible(false);
        checkFacade = new CheckFacade();
    }

    public void viewScores() {
        ScoreView score = new ScoreView();
        score.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desk = new javax.swing.JPanel();
        start1Player = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        jBScores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Start Menu");
        setUndecorated(true);

        Desk.setBackground(java.awt.Color.black);

        start1Player.setBackground(new java.awt.Color(53, 186, 243));
        start1Player.setFont(new java.awt.Font("KenVector Future Thin", 0, 18)); // NOI18N
        start1Player.setForeground(new java.awt.Color(0, 0, 0));
        start1Player.setText("START GAME");
        start1Player.setBorder(null);
        start1Player.setBorderPainted(false);
        start1Player.setFocusPainted(false);
        start1Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start1PlayerActionPerformed(evt);
            }
        });

        Return.setBackground(new java.awt.Color(53, 186, 243));
        Return.setFont(new java.awt.Font("KenVector Future Thin", 0, 18)); // NOI18N
        Return.setForeground(new java.awt.Color(0, 0, 0));
        Return.setText("RETURN");
        Return.setBorder(null);
        Return.setBorderPainted(false);
        Return.setFocusPainted(false);
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        jBScores.setBackground(new java.awt.Color(53, 186, 243));
        jBScores.setFont(new java.awt.Font("KenVector Future Thin", 0, 18)); // NOI18N
        jBScores.setForeground(new java.awt.Color(0, 0, 0));
        jBScores.setText("High Scores");
        jBScores.setBorder(null);
        jBScores.setBorderPainted(false);
        jBScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBScoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeskLayout = new javax.swing.GroupLayout(Desk);
        Desk.setLayout(DeskLayout);
        DeskLayout.setHorizontalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeskLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBScores, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start1Player, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
        );
        DeskLayout.setVerticalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeskLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(start1Player, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jBScores, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start1PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start1PlayerActionPerformed
        // TODO add your handling code here:
        //mode = true;
        startGame();
        this.setVisible(false);
    }//GEN-LAST:event_start1PlayerActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        exitGame();
        checkFacade.setVisible(true);
    }//GEN-LAST:event_ReturnActionPerformed

    private void jBScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBScoresActionPerformed

        viewScores();
    }//GEN-LAST:event_jBScoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desk;
    private javax.swing.JButton Return;
    private javax.swing.JButton jBScores;
    private javax.swing.JButton start1Player;
    // End of variables declaration//GEN-END:variables
}
