/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Snail;

import Facade.CheckFacade;

public class StartMenu extends javax.swing.JFrame {

    
    private SnailGame snailGame;
    private CheckFacade checkFacade;
    boolean mode;
    
    public StartMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desk = new javax.swing.JPanel();
        start1Player = new javax.swing.JButton();
        start2Players = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jBScores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Start Menu");

        Desk.setBackground(java.awt.Color.black);

        start1Player.setBackground(new java.awt.Color(0, 102, 0));
        start1Player.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        start1Player.setForeground(java.awt.Color.white);
        start1Player.setText("START 1 PLAYER");
        start1Player.setBorder(null);
        start1Player.setBorderPainted(false);
        start1Player.setFocusPainted(false);
        start1Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start1PlayerActionPerformed(evt);
            }
        });

        start2Players.setBackground(new java.awt.Color(0, 102, 0));
        start2Players.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        start2Players.setForeground(java.awt.Color.white);
        start2Players.setText("START 2 PLAYERS");
        start2Players.setBorder(null);
        start2Players.setBorderPainted(false);
        start2Players.setFocusPainted(false);
        start2Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start2PlayersActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(153, 0, 0));
        Exit.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        Exit.setForeground(java.awt.Color.white);
        Exit.setText("EXIT");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setFocusPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jBScores.setBackground(new java.awt.Color(0, 102, 0));
        jBScores.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jBScores.setForeground(java.awt.Color.white);
        jBScores.setText("High Scores");
        jBScores.setBorder(null);
        jBScores.setBorderPainted(false);
        jBScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBScoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeskLayout = new javax.swing.GroupLayout(Desk);
        Desk.setLayout(DeskLayout);
        DeskLayout.setHorizontalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeskLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBScores, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start2Players, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start1Player, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
        );
        DeskLayout.setVerticalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeskLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(start1Player, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start2Players, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBScores, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start1PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start1PlayerActionPerformed
        // TODO add your handling code here:
        mode = true;
        new SnailGame().start(mode);
        this.setVisible(false);
        
    }//GEN-LAST:event_start1PlayerActionPerformed

    private void start2PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start2PlayersActionPerformed
        // TODO add your handling code here:
        mode = false;
        new SnailGame().start(mode);
        this.setVisible(false);
    }//GEN-LAST:event_start2PlayersActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        checkFacade = new CheckFacade();
        checkFacade.setVisible(true);
    }//GEN-LAST:event_ExitActionPerformed

    private void jBScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBScoresActionPerformed
    
        ScoreView score = new ScoreView();
        score.setVisible(true);
    }//GEN-LAST:event_jBScoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desk;
    private javax.swing.JButton Exit;
    private javax.swing.JButton jBScores;
    private javax.swing.JButton start1Player;
    private javax.swing.JButton start2Players;
    // End of variables declaration//GEN-END:variables
}
